### ISSUE TITLE
plex and emby install / restore error , maybe more apps

### ISSUE THREAD

**Issue by dan3805** [dockserver/apps#18]
`Error response from daemon: Conflict. The container name "/plex" is already in use by container "83510eaaf3df1255faad2ecbf6e645c884df7d17ec00423ba61d344578e3d0a4". You have to remove (or rename) that container to be able to reuse that name.`

```
[RUN] Folder exist || set now permissions on /tmp/docker_backup

[RUN] Folder exist || set now permissions on /mnt/downloads/docker_backup

[RUN] Folder exist || set now permissions on /opt/appdata

[RUN] Folder exist || set now permissions on /mnt/unionfs/docker_backup

[RUN] Folder exist || set now permissions on /tmp/pulls

[RUN] Folder not exist || create now %s

[RUN] install plex .....
WARN[0000] The "PLEX_CLAIM_ID" variable is not set. Defaulting to a blank string.
Warning: No resource found to remove for project "plex".
WARN[0000] The "PLEX_CLAIM_ID" variable is not set. Defaulting to a blank string.
[+] Running 1/1
 ⠿ plex Pulled                                                                                                                                          0.4s

[RUN] install plex with override composer .....
WARN[0000] The "PLEX_CLAIM_ID" variable is not set. Defaulting to a blank string.
[+] Running 1/1
 ⠿ plex Pulled                                                                                                                                          0.4s
WARN[0000] The "PLEX_CLAIM_ID" variable is not set. Defaulting to a blank string.
[+] Running 0/0
 ⠋ Container plex  Creating                                                                                                                             0.0s
Error response from daemon: Conflict. The container name "/plex" is already in use by container "83510eaaf3df1255faad2ecbf6e645c884df7d17ec00423ba61d344578e3d0a4". You have to remove (or rename) that container to be able to reuse that name.
```
appinstall install plex :
![image](https://user-images.githubusercontent.com/35934387/189466572-d0760d53-0ba4-4f8a-a71e-af8e8d69482b.png)
appinstall restoreon plex :
![image](https://user-images.githubusercontent.com/35934387/189466636-a99f98da-437f-401c-9000-aefb0982cac0.png)

**Comment by fscorrupt** [comment]
this should already be fixed since a few months!

[b53e610](https://github.com/dockserver/dockserver/commit/b53e610c7f23846635ed173b9e9d5743b0849241)
[2c0e014](https://github.com/dockserver/dockserver/commit/2c0e0147b9dbf988674f6fc9f5c05970b3218d0c)
[2844e52](https://github.com/dockserver/dockserver/commit/2844e52c9ecc1a94f552f0b910fa019372aa9181)
[24ded1f](https://github.com/dockserver/dockserver/commit/24ded1fbd15a88fbddbd2e3b110e12b7dd5d9516)
[a08165b](https://github.com/dockserver/dockserver/commit/a08165b43f032dc9e9063abe8b08b4ea02a1ba39)
